import 'dart:async';

import 'package:editor/editor/document.dart';
import 'package:editor/services/websocket/models/lsp_autogenerated/language_server_protocol/lib/protocol_generated.dart';
import 'package:editor/services/websocket/models/server_class_defs/diff_change.dart';
import 'package:editor/services/websocket/models/server_class_defs/message_types.dart';

abstract class RemoteConnection {
  Stream<ServerMessage>? messages;
  StreamSubscription? subscription;

  /// Expects URL in the format: wss://a.b.c or ws://a.b.c
  void connect({required String serverUrl});

  void disconnect();

  void openFile({required Uri path});

  void closeFile({required Document document});

  void getDirectory({required Uri path});

  void getWorkingDirectory();

  void refreshDirectory({required Uri path});

  void changeFile(
      {required Document document, required List<DiffChange> changes});

  void saveFile({required Document document});

  void completion({required Document document, required Position position});

  void hover({required Document document, required Position position});

  void definition({required Document document, required Position position});

  void search({required String search, bool searchContent = false});
  void cancelSearch();

  void renameFile({required String oldPath, required String newPath});
  void renameDirectory({required String oldPath, required String newPath});
  void createFile({required String path});
  void createDirectory({required String path});
  void deleteFile({required String path});
  void deleteDirectory({required String path});
}
